updates:
- directory: edge/nodejs/hello-world/hello-world
  package-ecosystem: npm
  schedule:
    interval: daily
- directory: edge/nodejs/sam-app-python/sam-app-python
  package-ecosystem: pip
  schedule:
    interval: daily
version: 2
