name: "Dependa Test"

on:
  push:
    branches:
    - main 

jobs:
  pr-check:
    name: dependa-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: echo 'Test success'