name: nodejs code check

on:
  # TODO change to pull request 
  push:
    branches:
    - main

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          workdir: 'edge/nodejs/helloWorld/hello-world/'
