name: "pull request target test"

on:
  # pull_request_target:
  #   types: [ labeled ]
  push:
    branches:
    - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    # - name: test
    #   run: ./scripts/test.sh
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: s3 operation
      run: aws s3 cp scripts/update-dependabot-config.sh s3://sa-launch-mingtong